# Global Site Information
title: Jeremy Boggs
author: Jeremy Boggs
url: "http://jeremyboggs.net"
baseurl: ""

# Jekyll Settings
permalink: /:categories/:title/
exclude: ['readme.md', '.gitignore', '.sass-cache', 'Gemfile', 'Gemfile.lock', '_linked-data']
show_drafts: false
plugins: ['jekyll-feed', 'jekyll-sitemap']
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      bodyclass: "post"
  -
    scope:
      path: ""
      type: "courses"
    values:
      layout: "post"
      bodyclass: "course"


# Collections
collections:
  courses:
    output: true
    permalink: /courses/:title/

